#!/usr/bin/env node

/**
 * ATS Keyword Score — based on Resume-Matcher's scoring algorithm
 *
 * Usage: node ats_score.js <resume-text-file> <jd-keywords.json>
 *
 * jd-keywords.json format (generated by agent from JD):
 * {
 *   "required_skills": ["Python", "AWS"],
 *   "preferred_skills": ["Kubernetes"],
 *   "keywords": ["microservices", "agile"]
 * }
 *
 * Output: JSON with score, matched/missing keywords, and AI phrase warnings
 */

const fs = require('fs');

// --- AI phrase blacklist (from Resume-Matcher's refinement.py) ---
const AI_PHRASE_REPLACEMENTS = {
  'spearheaded': 'led',
  'leveraged': 'used',
  'utilized': 'used',
  'orchestrated': 'managed',
  'synergized': 'worked with',
  'revolutionized': 'improved',
  'transformed': 'changed',
  'pioneered': 'started',
  'championed': 'supported',
  'cultivated': 'built',
  'streamlined': 'simplified',
  'operationalized': 'implemented',
  'conceptualized': 'designed',
  'spearhead': 'lead',
  'leverage': 'use',
  'utilize': 'use',
  'orchestrate': 'manage',
  'cutting-edge': 'modern',
  'state-of-the-art': 'modern',
  'best-in-class': 'top',
  'world-class': 'top',
  'next-generation': 'new',
  'game-changing': 'significant',
  'groundbreaking': 'new',
  'paradigm shift': 'change',
  'deep dive': 'analysis',
  'synergy': 'collaboration',
  'holistic approach': 'complete approach',
  'robust solution': 'reliable solution',
  'scalable solution': 'solution that scales',
  'mission-critical': 'important',
  'bleeding-edge': 'latest',
  'thought leadership': 'expertise',
  'value proposition': 'benefit',
  'core competency': 'key skill',
  'strategic initiative': 'project',
  'cross-functional collaboration': 'teamwork across teams',
  'end-to-end ownership': 'full responsibility',
  'passionate about': 'interested in',
  'drove innovation': 'improved',
  'delivered impact': 'made a difference',
  'impactful solutions': 'effective solutions',
};

const AI_PATTERN_WARNINGS = [
  { pattern: /\b\w+ing\s+\w+ing\s+\w+ing\b/gi, label: 'Triple gerund chain' },
  { pattern: /\b(?:passionate|driven|motivated|dedicated|committed)\s+(?:about|to)\b/gi, label: 'Generic filler phrase' },
  { pattern: /\bensuring\s+\w+\s+while\s+\w+ing\b/gi, label: 'Gerund + while + gerund pattern' },
  { pattern: /\b(?:deliver(?:ing|ed)?|driv(?:ing|en)?)\s+(?:impactful|meaningful|transformative|innovative)\b/gi, label: 'AI buzzword combo' },
];

// --- Core matching (from Resume-Matcher's refiner.py) ---
function keywordInText(keyword, text) {
  const escaped = keyword.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const pattern = new RegExp(`\\b${escaped}\\b`, 'i');
  return pattern.test(text);
}

function calculateScore(resumeText, jdKeywords) {
  const allKeywords = new Set([
    ...(jdKeywords.required_skills || []),
    ...(jdKeywords.preferred_skills || []),
    ...(jdKeywords.keywords || []),
  ]);

  if (allKeywords.size === 0) return { score: 0, matched: [], missing: [], total: 0 };

  const matched = [];
  const missing = [];

  for (const kw of allKeywords) {
    if (keywordInText(kw, resumeText)) {
      matched.push(kw);
    } else {
      missing.push(kw);
    }
  }

  return {
    score: Math.round((matched.length / allKeywords.size) * 100),
    matched,
    missing,
    total: allKeywords.size,
  };
}

// --- AI phrase detection ---
function detectAIPhrases(resumeText) {
  const found = [];
  const textLower = resumeText.toLowerCase();

  for (const [phrase, replacement] of Object.entries(AI_PHRASE_REPLACEMENTS)) {
    if (textLower.includes(phrase.toLowerCase())) {
      found.push({ phrase, replacement });
    }
  }

  const patterns = [];
  for (const { pattern, label } of AI_PATTERN_WARNINGS) {
    const matches = resumeText.match(pattern);
    if (matches) {
      patterns.push({ label, examples: matches.slice(0, 3) });
    }
  }

  return { phrases: found, patterns };
}

// --- Main ---
const resumePath = process.argv[2];
const keywordsPath = process.argv[3];

if (!resumePath || !keywordsPath) {
  console.error('Usage: node ats_score.js <resume-text-file> <jd-keywords.json>');
  process.exit(1);
}

const resumeText = fs.readFileSync(resumePath, 'utf8');
const jdKeywords = JSON.parse(fs.readFileSync(keywordsPath, 'utf8'));

const score = calculateScore(resumeText, jdKeywords);
const aiCheck = detectAIPhrases(resumeText);

const result = {
  ats_score: score.score,
  matched_keywords: score.matched,
  missing_keywords: score.missing,
  total_keywords: score.total,
  ai_phrases_found: aiCheck.phrases,
  ai_patterns_found: aiCheck.patterns,
  recommendation: score.score >= 80 ? 'GOOD' : score.score >= 60 ? 'NEEDS_IMPROVEMENT' : 'LOW_MATCH',
};

console.log(JSON.stringify(result, null, 2));
